name: exoworlds
description: A Flutter app to explore exoplanets and their missions.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.1
  glassmorphism: ^3.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/AlienPlanet2.obj
    - assets/AlienPlanet2.mtl
    - assets/planet_Quom1200.png
